// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZnIEkPt19uF-KN9qPIF7GLurjZRoDJ6E',
    appId: '1:529800337851:web:0671a2cbab597d7cc58c9e',
    messagingSenderId: '529800337851',
    projectId: 'payrestroomtracker',
    authDomain: 'payrestroomtracker.firebaseapp.com',
    storageBucket: 'payrestroomtracker.appspot.com',
    measurementId: 'G-MSW76ML31V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidpaZx1Xs_jQh1HgL2B1eWNdjVRZuHkk',
    appId: '1:529800337851:android:b4178b96087692d1c58c9e',
    messagingSenderId: '529800337851',
    projectId: 'payrestroomtracker',
    storageBucket: 'payrestroomtracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaTDDLbczUD4BWgdPZkEEy_kOvQTX6bf8',
    appId: '1:529800337851:ios:6965908653941391c58c9e',
    messagingSenderId: '529800337851',
    projectId: 'payrestroomtracker',
    storageBucket: 'payrestroomtracker.appspot.com',
    androidClientId: '529800337851-tuc24i9sei000mjb2fsn9d9721qr5lc5.apps.googleusercontent.com',
    iosClientId: '529800337851-676jq15l9980076kva3vp1p7gdtbr62l.apps.googleusercontent.com',
    iosBundleId: 'com.example.payrestroomtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaTDDLbczUD4BWgdPZkEEy_kOvQTX6bf8',
    appId: '1:529800337851:ios:6965908653941391c58c9e',
    messagingSenderId: '529800337851',
    projectId: 'payrestroomtracker',
    storageBucket: 'payrestroomtracker.appspot.com',
    androidClientId: '529800337851-tuc24i9sei000mjb2fsn9d9721qr5lc5.apps.googleusercontent.com',
    iosClientId: '529800337851-676jq15l9980076kva3vp1p7gdtbr62l.apps.googleusercontent.com',
    iosBundleId: 'com.example.payrestroomtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZnIEkPt19uF-KN9qPIF7GLurjZRoDJ6E',
    appId: '1:529800337851:web:4bb3b2ed1425a2f8c58c9e',
    messagingSenderId: '529800337851',
    projectId: 'payrestroomtracker',
    authDomain: 'payrestroomtracker.firebaseapp.com',
    storageBucket: 'payrestroomtracker.appspot.com',
    measurementId: 'G-F7SJ2P0X3N',
  );
}
